export const EGYPT_GOVERNORATES: { name: string; nameAr: string; cities: { name: string; nameAr: string }[] }[] = [
  {
    name: "Cairo",
    nameAr: "القاهرة",
    cities: [
      { name: "Nasr City", nameAr: "مدينة نصر" },
      { name: "Heliopolis", nameAr: "مصر الجديدة" },
      { name: "Maadi", nameAr: "المعادي" },
      { name: "Zamalek", nameAr: "الزمالك" },
      { name: "Downtown", nameAr: "وسط البلد" },
      { name: "Shubra", nameAr: "شبرا" },
      { name: "Ain Shams", nameAr: "عين شمس" },
      { name: "New Cairo", nameAr: "القاهرة الجديدة" },
      { name: "Madinaty", nameAr: "مدينتي" },
      { name: "Helwan", nameAr: "حلوان" },
      { name: "Mokattam", nameAr: "المقطم" },
      { name: "El Marg", nameAr: "المرج" },
      { name: "El Salam", nameAr: "السلام" },
      { name: "El Basatin", nameAr: "البساتين" },
      { name: "Dokki", nameAr: "الدقي" },
    ],
  },
  {
    name: "Giza",
    nameAr: "الجيزة",
    cities: [
      { name: "6th of October", nameAr: "السادس من أكتوبر" },
      { name: "Sheikh Zayed", nameAr: "الشيخ زايد" },
      { name: "Dokki", nameAr: "الدقي" },
      { name: "Agouza", nameAr: "العجوزة" },
      { name: "Haram", nameAr: "الهرم" },
      { name: "Faisal", nameAr: "فيصل" },
      { name: "Mohandessin", nameAr: "المهندسين" },
      { name: "Imbaba", nameAr: "إمبابة" },
      { name: "Bulaq al-Dakrur", nameAr: "بولاق الدكرور" },
      { name: "Al Badrashin", nameAr: "البدرشين" },
      { name: "Al Ayyat", nameAr: "العياط" },
      { name: "Atfih", nameAr: "أطفيح" },
    ],
  },
  {
    name: "Alexandria",
    nameAr: "الإسكندرية",
    cities: [
      { name: "Montaza", nameAr: "المنتزه" },
      { name: "Miami", nameAr: "ميامي" },
      { name: "Smouha", nameAr: "سموحة" },
      { name: "Sidi Gaber", nameAr: "سيدي جابر" },
      { name: "Stanley", nameAr: "ستانلي" },
      { name: "Gleem", nameAr: "جليم" },
      { name: "Sporting", nameAr: "سبورتنج" },
      { name: "Roushdy", nameAr: "رشدي" },
      { name: "Camp Caesar", nameAr: "كامب شيزار" },
      { name: "Al Attarin", nameAr: "العطارين" },
      { name: "Bahari", nameAr: "بحري" },
      { name: "Borg El Arab", nameAr: "برج العرب" },
      { name: "Agami", nameAr: "العجمي" },
      { name: "Amreya", nameAr: "العامرية" },
    ],
  },
  {
    name: "Qalyubia",
    nameAr: "القليوبية",
    cities: [
      { name: "Banha", nameAr: "بنها" },
      { name: "Shubra El Kheima", nameAr: "شبرا الخيمة" },
      { name: "Qalyub", nameAr: "قليوب" },
      { name: "Khanka", nameAr: "الخانكة" },
      { name: "Al Khanka", nameAr: "الخانكة" },
      { name: "Toukh", nameAr: "طوخ" },
      { name: "Qaha", nameAr: "قها" },
      { name: "Shibin El Qanater", nameAr: "شبين القناطر" },
    ],
  },
  {
    name: "Port Said",
    nameAr: "بورسعيد",
    cities: [
      { name: "Port Said", nameAr: "بورسعيد" },
      { name: "Port Fuad", nameAr: "بورفؤاد" },
      { name: "El Zohour", nameAr: "الزهور" },
      { name: "El Manakh", nameAr: "المناخ" },
    ],
  },
  {
    name: "Suez",
    nameAr: "السويس",
    cities: [
      { name: "Suez", nameAr: "السويس" },
      { name: "Ataqa", nameAr: "عتاقة" },
      { name: "Arbaeen", nameAr: "الأربعين" },
      { name: "Ganayen", nameAr: "الجناين" },
    ],
  },
  {
    name: "Dakahlia",
    nameAr: "الدقهلية",
    cities: [
      { name: "Mansoura", nameAr: "المنصورة" },
      { name: "Talkha", nameAr: "طلخا" },
      { name: "Mit Ghamr", nameAr: "ميت غمر" },
      { name: "Aga", nameAr: "أجا" },
      { name: "Dekernes", nameAr: "دكرنس" },
      { name: "Sherbin", nameAr: "شربين" },
      { name: "Mataria", nameAr: "المطرية" },
      { name: "Belqas", nameAr: "بلقاس" },
      { name: "Sinbillawin", nameAr: "السنبلاوين" },
      { name: "Nabaroh", nameAr: "نبروه" },
      { name: "Manzala", nameAr: "المنزلة" },
      { name: "Gamasa", nameAr: "جمصة" },
    ],
  },
  {
    name: "Sharqia",
    nameAr: "الشرقية",
    cities: [
      { name: "Zagazig", nameAr: "الزقازيق" },
      { name: "10th of Ramadan", nameAr: "العاشر من رمضان" },
      { name: "Belbeis", nameAr: "بلبيس" },
      { name: "Abu Kabir", nameAr: "أبو كبير" },
      { name: "Faqous", nameAr: "فاقوس" },
      { name: "Minya Al Qamh", nameAr: "منيا القمح" },
      { name: "Kafr Saqr", nameAr: "كفر صقر" },
      { name: "Diyarb Negm", nameAr: "ديرب نجم" },
      { name: "Hihya", nameAr: "ههيا" },
      { name: "Awlad Saqr", nameAr: "أولاد صقر" },
    ],
  },
  {
    name: "Gharbia",
    nameAr: "الغربية",
    cities: [
      { name: "Tanta", nameAr: "طنطا" },
      { name: "El Mahalla El Kubra", nameAr: "المحلة الكبرى" },
      { name: "Kafr El Zayat", nameAr: "كفر الزيات" },
      { name: "Zefta", nameAr: "زفتى" },
      { name: "Samannoud", nameAr: "سمنود" },
      { name: "Basyoun", nameAr: "بسيون" },
      { name: "Qutur", nameAr: "قطور" },
    ],
  },
  {
    name: "Monufia",
    nameAr: "المنوفية",
    cities: [
      { name: "Shibin El Kom", nameAr: "شبين الكوم" },
      { name: "Menouf", nameAr: "منوف" },
      { name: "Sadat City", nameAr: "مدينة السادات" },
      { name: "Ashmoun", nameAr: "أشمون" },
      { name: "Quesna", nameAr: "قويسنا" },
      { name: "Tala", nameAr: "تلا" },
      { name: "Berket El Sabaa", nameAr: "بركة السبع" },
    ],
  },
  {
    name: "Beheira",
    nameAr: "البحيرة",
    cities: [
      { name: "Damanhur", nameAr: "دمنهور" },
      { name: "Kafr El Dawwar", nameAr: "كفر الدوار" },
      { name: "Rashid (Rosetta)", nameAr: "رشيد" },
      { name: "Edku", nameAr: "إدكو" },
      { name: "Abu Hummus", nameAr: "أبو حمص" },
      { name: "Kom Hamada", nameAr: "كوم حمادة" },
      { name: "Itay El Baroud", nameAr: "إيتاي البارود" },
      { name: "Hosh Isa", nameAr: "حوش عيسى" },
    ],
  },
  {
    name: "Ismailia",
    nameAr: "الإسماعيلية",
    cities: [
      { name: "Ismailia", nameAr: "الإسماعيلية" },
      { name: "Fayed", nameAr: "فايد" },
      { name: "Qantara Sharq", nameAr: "القنطرة شرق" },
      { name: "Qantara Gharb", nameAr: "القنطرة غرب" },
      { name: "Abu Suwir", nameAr: "أبو صوير" },
      { name: "Tell El Kebir", nameAr: "التل الكبير" },
    ],
  },
  {
    name: "Kafr El Sheikh",
    nameAr: "كفر الشيخ",
    cities: [
      { name: "Kafr El Sheikh", nameAr: "كفر الشيخ" },
      { name: "Desouk", nameAr: "دسوق" },
      { name: "Fuwwah", nameAr: "فوة" },
      { name: "Baltim", nameAr: "بلطيم" },
      { name: "Sidi Salem", nameAr: "سيدي سالم" },
      { name: "Metoubes", nameAr: "مطوبس" },
      { name: "Qallin", nameAr: "قلين" },
      { name: "Bila", nameAr: "بيلا" },
    ],
  },
  {
    name: "Damietta",
    nameAr: "دمياط",
    cities: [
      { name: "Damietta", nameAr: "دمياط" },
      { name: "New Damietta", nameAr: "دمياط الجديدة" },
      { name: "Ras El Bar", nameAr: "رأس البر" },
      { name: "Faraskur", nameAr: "فارسكور" },
      { name: "Kafr Saad", nameAr: "كفر سعد" },
      { name: "Zarqa", nameAr: "الزرقا" },
    ],
  },
  {
    name: "Faiyum",
    nameAr: "الفيوم",
    cities: [
      { name: "Faiyum", nameAr: "الفيوم" },
      { name: "Sinnuris", nameAr: "سنورس" },
      { name: "Tamiya", nameAr: "طامية" },
      { name: "Ibsheway", nameAr: "إبشواي" },
      { name: "Itsa", nameAr: "إطسا" },
      { name: "Yousef El Seddik", nameAr: "يوسف الصديق" },
    ],
  },
  {
    name: "Beni Suef",
    nameAr: "بني سويف",
    cities: [
      { name: "Beni Suef", nameAr: "بني سويف" },
      { name: "El Wasta", nameAr: "الواسطى" },
      { name: "Nasser", nameAr: "ناصر" },
      { name: "Ihnasia", nameAr: "إهناسيا" },
      { name: "Biba", nameAr: "ببا" },
      { name: "Fashn", nameAr: "الفشن" },
      { name: "Somasta", nameAr: "سمسطا" },
    ],
  },
  {
    name: "Minya",
    nameAr: "المنيا",
    cities: [
      { name: "Minya", nameAr: "المنيا" },
      { name: "Mallawi", nameAr: "ملوي" },
      { name: "Beni Mazar", nameAr: "بني مزار" },
      { name: "Maghagha", nameAr: "مغاغة" },
      { name: "Samalut", nameAr: "سمالوط" },
      { name: "Matai", nameAr: "مطاي" },
      { name: "Abu Qurqas", nameAr: "أبو قرقاص" },
      { name: "Deir Mawas", nameAr: "دير مواس" },
    ],
  },
  {
    name: "Asyut",
    nameAr: "أسيوط",
    cities: [
      { name: "Asyut", nameAr: "أسيوط" },
      { name: "Dairut", nameAr: "ديروط" },
      { name: "Manfalut", nameAr: "منفلوط" },
      { name: "Abnub", nameAr: "أبنوب" },
      { name: "Abu Tig", nameAr: "أبوتيج" },
      { name: "Sahel Selim", nameAr: "ساحل سليم" },
      { name: "Al Ghanayem", nameAr: "الغنايم" },
      { name: "Al Qusiya", nameAr: "القوصية" },
    ],
  },
  {
    name: "Sohag",
    nameAr: "سوهاج",
    cities: [
      { name: "Sohag", nameAr: "سوهاج" },
      { name: "Akhmim", nameAr: "أخميم" },
      { name: "Girga", nameAr: "جرجا" },
      { name: "Tahta", nameAr: "طهطا" },
      { name: "Tama", nameAr: "طما" },
      { name: "Al Balyana", nameAr: "البلينا" },
      { name: "Al Maragha", nameAr: "المراغة" },
      { name: "Juhayna", nameAr: "جهينة" },
    ],
  },
  {
    name: "Qena",
    nameAr: "قنا",
    cities: [
      { name: "Qena", nameAr: "قنا" },
      { name: "Nag Hammadi", nameAr: "نجع حمادي" },
      { name: "Qus", nameAr: "قوص" },
      { name: "Naqada", nameAr: "نقادة" },
      { name: "Deshna", nameAr: "دشنا" },
      { name: "Abu Tesht", nameAr: "أبوتشت" },
      { name: "Farshut", nameAr: "فرشوط" },
    ],
  },
  {
    name: "Luxor",
    nameAr: "الأقصر",
    cities: [
      { name: "Luxor", nameAr: "الأقصر" },
      { name: "Esna", nameAr: "إسنا" },
      { name: "Armant", nameAr: "أرمنت" },
      { name: "Al Bayadiya", nameAr: "البياضية" },
      { name: "Al Tud", nameAr: "الطود" },
      { name: "Al Zeniya", nameAr: "الزينية" },
    ],
  },
  {
    name: "Aswan",
    nameAr: "أسوان",
    cities: [
      { name: "Aswan", nameAr: "أسوان" },
      { name: "Kom Ombo", nameAr: "كوم أمبو" },
      { name: "Edfu", nameAr: "إدفو" },
      { name: "Daraw", nameAr: "دراو" },
      { name: "Nasr El Nuba", nameAr: "نصر النوبة" },
      { name: "Abu Simbel", nameAr: "أبو سمبل" },
    ],
  },
  {
    name: "Red Sea",
    nameAr: "البحر الأحمر",
    cities: [
      { name: "Hurghada", nameAr: "الغردقة" },
      { name: "El Gouna", nameAr: "الجونة" },
      { name: "Safaga", nameAr: "سفاجا" },
      { name: "El Quseir", nameAr: "القصير" },
      { name: "Marsa Alam", nameAr: "مرسى علم" },
      { name: "Ras Ghareb", nameAr: "رأس غارب" },
      { name: "Shalateen", nameAr: "شلاتين" },
    ],
  },
  {
    name: "New Valley",
    nameAr: "الوادي الجديد",
    cities: [
      { name: "Kharga", nameAr: "الخارجة" },
      { name: "Dakhla", nameAr: "الداخلة" },
      { name: "Farafra", nameAr: "الفرافرة" },
      { name: "Paris", nameAr: "باريس" },
    ],
  },
  {
    name: "Matrouh",
    nameAr: "مطروح",
    cities: [
      { name: "Marsa Matrouh", nameAr: "مرسى مطروح" },
      { name: "El Alamein", nameAr: "العلمين" },
      { name: "Siwa", nameAr: "سيوة" },
      { name: "El Dabaa", nameAr: "الضبعة" },
      { name: "Sidi Barrani", nameAr: "سيدي براني" },
      { name: "Salloum", nameAr: "السلوم" },
    ],
  },
  {
    name: "North Sinai",
    nameAr: "شمال سيناء",
    cities: [
      { name: "Arish", nameAr: "العريش" },
      { name: "Sheikh Zuweid", nameAr: "الشيخ زويد" },
      { name: "Rafah", nameAr: "رفح" },
      { name: "Bir al-Abd", nameAr: "بئر العبد" },
      { name: "Nakhl", nameAr: "نخل" },
    ],
  },
  {
    name: "South Sinai",
    nameAr: "جنوب سيناء",
    cities: [
      { name: "Sharm El Sheikh", nameAr: "شرم الشيخ" },
      { name: "Dahab", nameAr: "دهب" },
      { name: "Nuweiba", nameAr: "نويبع" },
      { name: "Taba", nameAr: "طابا" },
      { name: "Saint Catherine", nameAr: "سانت كاترين" },
      { name: "Ras Sedr", nameAr: "رأس سدر" },
      { name: "Abu Zenima", nameAr: "أبو زنيمة" },
    ],
  },
];
