export const EGYPT_GOVERNORATES: { name: string; cities: string[] }[] = [
  {
    name: "Cairo",
    cities: [
      "Nasr City",
      "Heliopolis",
      "Maadi",
      "Zamalek",
      "Downtown",
      "Shubra",
      "Ain Shams",
      "New Cairo",
      "Madinaty",
      "Helwan",
      "Mokattam",
      "El Marg",
      "El Salam",
      "El Basatin",
      "Dokki",
    ],
  },
  {
    name: "Giza",
    cities: [
      "6th of October",
      "Sheikh Zayed",
      "Dokki",
      "Agouza",
      "Haram",
      "Faisal",
      "Mohandessin",
      "Imbaba",
      "Bulaq al-Dakrur",
      "Al Badrashin",
      "Al Ayyat",
      "Atfih",
    ],
  },
  {
    name: "Alexandria",
    cities: [
      "Montaza",
      "Miami",
      "Smouha",
      "Sidi Gaber",
      "Stanley",
      "Gleem",
      "Sporting",
      "Roushdy",
      "Camp Caesar",
      "Al Attarin",
      "Bahari",
      "Borg El Arab",
      "Agami",
      "Amreya",
    ],
  },
  {
    name: "Qalyubia",
    cities: ["Banha", "Shubra El Kheima", "Qalyub", "Khanka", "Al Khanka", "Toukh", "Qaha", "Shibin El Qanater"],
  },
  { name: "Port Said", cities: ["Port Said", "Port Fuad", "El Zohour", "El Manakh"] },
  { name: "Suez", cities: ["Suez", "Ataqa", "Arbaeen", "Ganayen"] },
  {
    name: "Dakahlia",
    cities: [
      "Mansoura",
      "Talkha",
      "Mit Ghamr",
      "Aga",
      "Dekernes",
      "Sherbin",
      "Mataria",
      "Belqas",
      "Sinbillawin",
      "Nabaroh",
      "Manzala",
      "Gamasa",
    ],
  },
  {
    name: "Sharqia",
    cities: [
      "Zagazig",
      "10th of Ramadan",
      "Belbeis",
      "Abu Kabir",
      "Faqous",
      "Minya Al Qamh",
      "Kafr Saqr",
      "Diyarb Negm",
      "Hihya",
      "Awlad Saqr",
    ],
  },
  {
    name: "Gharbia",
    cities: ["Tanta", "El Mahalla El Kubra", "Kafr El Zayat", "Zefta", "Samannoud", "Basyoun", "Qutur"],
  },
  {
    name: "Monufia",
    cities: ["Shibin El Kom", "Menouf", "Sadat City", "Ashmoun", "Quesna", "Tala", "Berket El Sabaa"],
  },
  {
    name: "Beheira",
    cities: [
      "Damanhur",
      "Kafr El Dawwar",
      "Rashid (Rosetta)",
      "Edku",
      "Abu Hummus",
      "Kom Hamada",
      "Itay El Baroud",
      "Hosh Isa",
    ],
  },
  { name: "Ismailia", cities: ["Ismailia", "Fayed", "Qantara Sharq", "Qantara Gharb", "Abu Suwir", "Tell El Kebir"] },
  {
    name: "Kafr El Sheikh",
    cities: ["Kafr El Sheikh", "Desouk", "Fuwwah", "Baltim", "Sidi Salem", "Metoubes", "Qallin", "Bila"],
  },
  { name: "Damietta", cities: ["Damietta", "New Damietta", "Ras El Bar", "Faraskur", "Kafr Saad", "Zarqa"] },
  { name: "Faiyum", cities: ["Faiyum", "Sinnuris", "Tamiya", "Ibsheway", "Itsa", "Yousef El Seddik"] },
  { name: "Beni Suef", cities: ["Beni Suef", "El Wasta", "Nasser", "Ihnasia", "Biba", "Fashn", "Somasta"] },
  {
    name: "Minya",
    cities: ["Minya", "Mallawi", "Beni Mazar", "Maghagha", "Samalut", "Matai", "Abu Qurqas", "Deir Mawas"],
  },
  {
    name: "Asyut",
    cities: ["Asyut", "Dairut", "Manfalut", "Abnub", "Abu Tig", "Sahel Selim", "Al Ghanayem", "Al Qusiya"],
  },
  {
    name: "Sohag",
    cities: ["Sohag", "Akhmim", "Girga", "Tahta", "Tama", "Al Balyana", "Al Maragha", "Juhayna"],
  },
  {
    name: "Qena",
    cities: ["Qena", "Nag Hammadi", "Qus", "Naqada", "Deshna", "Abu Tesht", "Farshut"],
  },
  { name: "Luxor", cities: ["Luxor", "Esna", "Armant", "Al Bayadiya", "Al Tud", "Al Zeniya"] },
  { name: "Aswan", cities: ["Aswan", "Kom Ombo", "Edfu", "Daraw", "Nasr El Nuba", "Abu Simbel"] },
  {
    name: "Red Sea",
    cities: ["Hurghada", "El Gouna", "Safaga", "El Quseir", "Marsa Alam", "Ras Ghareb", "Shalateen"],
  },
  { name: "New Valley", cities: ["Kharga", "Dakhla", "Farafra", "Paris"] },
  { name: "Matrouh", cities: ["Marsa Matrouh", "El Alamein", "Siwa", "El Dabaa", "Sidi Barrani", "Salloum"] },
  { name: "North Sinai", cities: ["Arish", "Sheikh Zuweid", "Rafah", "Bir al-Abd", "Nakhl"] },
  {
    name: "South Sinai",
    cities: ["Sharm El Sheikh", "Dahab", "Nuweiba", "Taba", "Saint Catherine", "Ras Sedr", "Abu Zenima"],
  },
];
